### ISSUE TITLE
Caused by: com.groupdocs.watermark.exceptions.FontNotFoundException

### ISSUE THREAD

**Issue by anyspa** [groupdocs-watermark/GroupDocs.Watermark-for-Java#16]
I am trying to use groupdocs.watermark to remove the watermark of PDF, here is my code：

`
 ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
 
 try (Watermarker watermarker = new Watermarker(filePath, new LoadOptions(pdfPassword))) {

     TextSearchCriteria textSearchCriteria = new TextSearchCriteria("Company Name");

     PossibleWatermarkCollection watermarks = watermarker.search(textSearchCriteria);
     
     if (watermarks.getCount() > 0) {
         watermarks.forEach(watermarker::remove);
     }  

     watermarker.save(outputStream);
 
  } catch (Exception e) {

     throw new RuntimeException("removeWaterMarker fail. ", e);

 } 
`

it works success on win10 ，but  when I deploy my project on centos and start， it throws FontNotFoundException like this:
Caused by: com.groupdocs.watermark.exceptions.FontNotFoundException
        at com.groupdocs.watermark.internal.aT.a(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.internal.aG.a(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.internal.aG.a(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.internal.bU.a(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.internal.bU.a(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.contents.PdfPage.addArtifactWatermark(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.contents.PdfContent.bQ(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.contents.Content.bR(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.contents.Content.save(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]
        at com.groupdocs.watermark.Watermarker.save(Unknown Source) ~[groupdocs-watermark-20.5.jar:20.5]

What Font not found？

**Comment by anyspa** [comment]
Solved
